### ISSUE TITLE
Ubuntu 24.04 incompatibility

### ISSUE THREAD

**Issue by ilbarone87** [ricsanfre/fluentd-aggregator#2]
Hello Ric
After I'update my RKE2 nodes to Ubuntu 24.04 i'm getting this error when fluentd is trying to start:

`Error: failed to create containerd container: mount callback failed on /var/lib/rancher/rke2/agent/containerd/tmpmounts/containerd-mount3992244989: no users found`

Can you please advise?

**Comment by ricsanfre** [comment]
Hi Giussepe, 

It is strange because that containerd error might be related with the use of a non-root user in the docker image (`fluent` user), but it should work not matter the release of the Ubuntu server. I am using v1.30 kubernetes release on Ubuntu 22.04 nodes and that image is working without issues. Which Kubernetes version are you using?

By the other hand base image might be a little out-dated for Ubuntu 24.04. Base image is adding some system libraries that could be quite old. You could try to rebuild the docker image usins a more recent version of base image, maybe v1.16 or v1.17



Regards
Ricardo

**Comment by ilbarone87** [comment]
Hi Ricardo,
yeah indeed i found it strange as well. My cluster is on 1.30.4 RKE2 stable release channel and was it working for me as well before the upgrade.

Adding this to the helm values sorted the problem:

`  securityContext:
   capabilities:
     drop:
     - ALL
   readOnlyRootFilesystem: false
   runAsNonRoot: true
   runAsUser: 1000`

On the other hand, as you suggested i tried to rebuild in the last few days the image with 1.16.6 or 1.17.1 (you can check it out in my repo as i forked yours) but using that image gives me this error:

`#0 config error file="/fluentd/etc/../../../etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="xpack endpoint does not work"`

let me know if you have any idea on how to solve this an update of the image is defo preferable.

Cheers,
Giuseppe

**Comment by ricsanfre** [comment]
Hi Giussepe, 

I have updated Dockerfile to use latest available fluend docker image v1.17.1. You can find new docker image in docker hub tagged as `v1.17.1-debian-1.0`

I also upgraded `fluentd-elasticsearch-plugin` to latest version, so it is not needed anymore to specify any of the elasticsearch  dependencies (including elastic-xpack). New version uses latest elasticearch-8.x related ruby gems. The workaround, using elastisearch-xpack and elasticsearch-7.x ruby gems, to make ILM policies work it is not needed. In fact, in the docker file only `fluentd-elasticsearch-plugin` need to be installed and automatically latest versions of elasticsearch gems are installed as dependencies.

I have tested it locally and it seems to work fine,  including all advance features, like ILM policies and data templates.

Regarding to additional `securityContext` configuration, it is strange that in 24.04 is required and not using Ubuntu 22.04. Since the image is using a non root user, `securityContext` spec should be mandatory. Do you have on your nodes any additional security configuration you did not have before, like SELinux? 

Regards
Ricardo

**Comment by ilbarone87** [comment]
Hi Ricardo
thank you for confirming that, i had the feeling that some of the gem plugin became redundant with ES 8.x. I'll adjust my image too.

Regarding 'securityContext', my Ubuntu server is vanilla i don't have any extra config added to it.
